name: Lint Terraform

on:
  push:
    branches:
      - main
      - master
      - production
      - staging
  pull_request:
    branches:
      - main
      - master
      - production
      - staging

jobs:
  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5.0"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        
      - name: Terraform Init
        run: terraform init -backend=false
        
      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0
          
      - name: Show TFLint version
        run: tflint --version
        
      - name: Init TFLint
        run: tflint --init
        
      - name: Run TFLint
        run: tflint -f compact